### ISSUE TITLE
Fetching error

### ISSUE THREAD

**Issue by Kxa422** [dcarroll/sublime-lightning#30]
After using the following command line

force fetch -t Aura -n InventoryList -d "C:\Work\Salesforce\test"

The following error appear, no firewall or proxy

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x42bab2]

goroutine 1 [running]:
main.(*Force).GetAuraBundleByName(0x0, 0xc0820022c0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:499 +0x592
main.(*Force).GetAuraBundle(0x0, 0xc0820022c0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:487 +0xb3
main.runFetchAura2(0xba1e80, 0xc0820022c0, 0xd)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:89 +0x164
main.runFetch(0xba1e80, 0xc082058070, 0x0, 0x0)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:200 +0x1aa
main.main()
        /home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9

**Comment by inakirzabalegui** [comment]
Did you figure out the issue? I have same problem with regular users in terminal but not with root/sudo

**Comment by dcarroll** [comment]
You need to make sure the user has access to the force cli executable.

Sent from my iPhone

On May 17, 2016, at 4:18 PM, inakirzabalegui <notifications@github.com>
wrote:

Did you figure out the issue? I have same problem with regular users in
terminal but not with root/sudo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/30#issuecomment-219751264>

**Comment by inakirzabalegui** [comment]
Yes, the access was no problem. In fact the user could login in the OAuth. problem was the login was not properly stored in the .force folder producing a segmentation fault because force cli assumes the login is present.
